# Generated by Django 4.1.5 on 2023-01-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('question', models.TextField(blank=True)),
                ('answer', models.TextField(blank=True)),
                ('timestamp_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('hash_pass', models.CharField(max_length=254)),
                ('timestamp_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
